### PR TITLE
Updates explaining how to use various scripts and maplists, corrected spelling mistakes in hints.txt, removed deprecated maps

### PR DESCRIPTION
**Pull request by t52ta6ek**
Added explanation how gm scripts are used with aprsmap
Added explanation how the use the various maps in the maplist files with aprsmap
Added sample commands showing wget2 and curl usage in updateDXLaprs and some general cleanup
Removed map deprecated by mapbox
Corrected some spelling mistakes in the hints.txt
73!

### CODE REVIEW

**Comment by t52ta6ek** [comment]
Greetings @oe5hpm !
requesting a review for pull request #39 .  Mainly updated comments and examples in the scripts.
Thanks again and 73!
Tom

**Comment by t52ta6ek** [comment]
Hello again @oe5hpm.  For the hints.txt file, I just fixed the problems that caught my eye, but it seems it could use a complete going over. I am willing to review all the hints at some point. Does a hints.txt file happen to exist in the original German?
73!
Tom

**Comment by oe5hpm** [comment]
hi, sorry for very late response. could you please update your pr ?

**Comment by t52ta6ek** [comment]
hello! to be honest, i use github so little, what do i need to do to update the pull request? ;-)
tnx!
tom

**Comment by oe5hpm** [comment]
your merge up to the latest changes did the job :-)

**Pull request merged**
